// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmrXOAGB8Bv2TjR7pq-RFU_WHoYLSmgE',
    appId: '1:679322510059:web:f99bddfdde220fec9894ae',
    messagingSenderId: '679322510059',
    projectId: 'doan1-464ff',
    authDomain: 'doan1-464ff.firebaseapp.com',
    storageBucket: 'doan1-464ff.firebasestorage.app',
    measurementId: 'G-JN4VR7VS3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArfomQULqBwZInZ0JzLumLRLMP8gYswr0',
    appId: '1:679322510059:android:8ba4df41dc5e20889894ae',
    messagingSenderId: '679322510059',
    projectId: 'doan1-464ff',
    storageBucket: 'doan1-464ff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Tm0WB1mlnrV-7mScAk_i1ig3Pf_31Rc',
    appId: '1:679322510059:ios:bf31df6236a9f4c39894ae',
    messagingSenderId: '679322510059',
    projectId: 'doan1-464ff',
    storageBucket: 'doan1-464ff.firebasestorage.app',
    iosBundleId: 'com.example.doan1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Tm0WB1mlnrV-7mScAk_i1ig3Pf_31Rc',
    appId: '1:679322510059:ios:bf31df6236a9f4c39894ae',
    messagingSenderId: '679322510059',
    projectId: 'doan1-464ff',
    storageBucket: 'doan1-464ff.firebasestorage.app',
    iosBundleId: 'com.example.doan1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjmrXOAGB8Bv2TjR7pq-RFU_WHoYLSmgE',
    appId: '1:679322510059:web:2218205863c2cee19894ae',
    messagingSenderId: '679322510059',
    projectId: 'doan1-464ff',
    authDomain: 'doan1-464ff.firebaseapp.com',
    storageBucket: 'doan1-464ff.firebasestorage.app',
    measurementId: 'G-X345NXD25W',
  );
}
